kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim-thin
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: thin
  volumeMode: Filesystem
