kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc-thin
  namespace: guestbook
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: thin
  volumeMode: Filesystem
